In [1]:
import cv2

In [2]:
path='tom&jerry.jpg'

In [3]:
tj=cv2.imread(path,1)

In [4]:
cv2.imshow('image',tj)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
print(tj.shape)
print(tj.size)
print(tj.dtype)

(450, 600, 3)
810000
uint8


In [6]:
pix=tj[50,50]
print(pix)

[103 165 211]


In [7]:
b,g,r=cv2.split(tj) # split into BGR channels 
print(b,g,r)
bl=tj[:,:,0] # split using numpy into BGR channels B-0,G-1,R-2
print('Blue')
print(bl)


[[110 111 111 ... 207 206  85]
 [108 108 109 ... 207 206  85]
 [105 105 105 ... 207 206  85]
 ...
 [ 77  77  77 ...  81  87   8]
 [ 78  79  79 ...  84  76  18]
 [ 50  50  50 ...  74  65   8]] [[177 178 178 ... 201 201  80]
 [175 175 176 ... 201 201  80]
 [173 173 173 ... 201 201  80]
 ...
 [163 163 163 ... 156 157  76]
 [160 161 161 ... 154 141  83]
 [132 132 132 ... 142 129  71]] [[226 227 227 ... 218 216  95]
 [224 224 225 ... 218 216  95]
 [220 220 220 ... 218 216  95]
 ...
 [103 103 103 ... 104 110  29]
 [107 108 108 ... 107  96  38]
 [ 80  80  80 ...  95  87  29]]
Blue
[[110 111 111 ... 207 206  85]
 [108 108 109 ... 207 206  85]
 [105 105 105 ... 207 206  85]
 ...
 [ 77  77  77 ...  81  87   8]
 [ 78  79  79 ...  84  76  18]
 [ 50  50  50 ...  74  65   8]]


In [8]:
img=cv2.merge((b,g,r)) # merge the BGR channels
cv2.imshow('merge',img) 
cv2.waitKey(0)

cv2.destroyAllWindows()

In [9]:
mo=cv2.imread(path,1)
mo[:,:,0]=0
cv2.imshow('Modified_color',mo)
cv2.imwrite('Modified_color.png',mo)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('CO',img)
cv2.imwrite('COLOR.png',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [11]:
for n in range (1,50):
    for m in range (1,50):
        for i in range (0,3):
            print(tj.item(m,n,i))
            tj.itemset((m,n,i),255)
cv2.imshow('Modified_pixel',tj)
cv2.imwrite('Modified_pixel.png',mo)
cv2.waitKey(0)
cv2.destroyAllWindows()

108
175
224
105
173
220
102
170
215
100
169
212
99
168
211
100
170
210
100
170
210
100
170
210
100
170
210
102
171
214
105
174
217
109
177
222
111
179
226
111
178
227
108
177
226
108
179
229
108
179
229
110
179
229
110
179
229
112
179
228
112
179
228
113
179
228
113
179
228
109
173
221
103
167
215
102
164
210
103
165
211
105
165
211
104
164
210
105
164
210
106
166
212
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
109
176
225
105
173
220
102
170
217
100
168
213
100
169
212
100
170
210
101
171
211
100
170
210
100
170
210
102
171
214
105
173
218
109
177
224
111
179
226
111
178
227
110
177
226
110
179
229
108
179
229
110
179
229
110
179
229
112
179
228
112
179
228
113
179
228
113
179
228
109
173
221
103
167
215
102
164
210
103
165
211
105
165
211
104
164
210
105
164
210
107
166
212
105
165
211
103
165
211
103
165
211
103
1

103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
112
178
229
113
180
229
112
180
227
108
176
221
104
173
216
101
171
211
100
170
210
102
172
212
101
171
211
101
171
211
103
173
213
107
176
219
110
178
223
112
180
227
110
180
227
108
180
228
107
179
227
109
179
226
110
180
227
113
181
228
112
180
227
111
178
223
109
176
221
105
170
215
103
168
213
103
166
210
102
165
209
105
166
210
106
167
211
107
166
211
105
166
210
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
112
178
231
114
180
231
112
179
228
108
176
223
104
172
217
101
170
213
100
170
210
102
172
212
101
171
211
101
171
211
103
172
215
107
175
220
110
178
223
112
180
227
112
180
227
110
179
228
107
179
227
109
179
226
110
180
227
113
181
228
112
180
227
111
178
223
109
176
221
105
170
215
103
168
213
103
166
210
102


170
213
104
169
214
106
171
216
110
174
222
113
176
226
112
177
228
113
179
230
113
179
230
112
178
229
113
179
228
114
180
229
111
177
226
105
171
220
102
166
214
101
165
213
100
165
210
100
165
210
104
166
212
104
166
212
103
165
211
102
164
210
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
110
179
229
110
179
228
110
180
227
111
179
224
108
177
220
104
174
214
100
170
210
101
170
210
102
171
211
102
171
211
102
171
211
104
169
213
106
171
216
110
174
222
111
177
225
111
178
227
113
179
230
113
179
230
112
178
229
113
179
228
114
180
229
111
177
226
105
171
220
102
166
214
101
165
213
100
165
210
100
165
210
104
166
212
104
166
212
103
165
211
102
164
210
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165
211
103
165


In [12]:
img=cv2.imread(path,1)
img=cv2.copyMakeBorder(img,5,5,5,5,cv2.BORDER_REPLICATE,value=[255,255,255])
cv2.imshow('im',img)
cv2.imwrite('border.png',img)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [13]:
import numpy
import os

randomByteArray= bytearray(os.urandom(120000))
flatNumpyArray=numpy.array(randomByteArray)
gray=flatNumpyArray.reshape(300,400)
cv2.imshow('img_gen',gray)
cv2.waitKey(0)
cv2.imwrite('img_gen.png',gray)
bgr=flatNumpyArray.reshape(200,200,3)
cv2.imshow('img_gen1',bgr)
cv2.imwrite('img_gen1.png',bgr)
cv2.waitKey(0)

cv2.destroyAllWindows()

# Region of Interest

In [14]:
jerry=tj[250:400,25:150]
cv2.imshow('imge',jerry)
cv2.imwrite('jerry.png',jerry)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [15]:
tj[300:450,200:325]=jerry # Move the interested portion
cv2.imshow('imge',tj)
cv2.imwrite('jerry_move.png',jerry)
cv2.waitKey(0)

cv2.destroyAllWindows()

# combine 2 images

In [16]:
gy=cv2.imread("D:/tech/Untitled Folder/galaxy.jpg",1)
ny=cv2.imread("D:/tech/Untitled Folder/noddy.jpg",1)

In [17]:
print(gy.shape)
print(ny.shape)

(339, 509, 3)
(900, 900, 3)


In [18]:
gy=cv2.resize(gy,(256,256))
ny=cv2.resize(ny,(256,256))
cv2.imshow('image',gy)
cv2.waitKey(0)
cv2.imshow('image1',ny)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Add

In [19]:
add=cv2.add(gy,ny);
cv2.imshow('image',add)
cv2.waitKey(0)
cv2.imwrite('combined.png',add)
cv2.destroyAllWindows()

In [20]:
add_w=cv2.addWeighted(gy,0.7,ny,0.3,0);
cv2.imshow('image',add_w)
cv2.waitKey(0)
cv2.imwrite('combined_w.png',add_w)
cv2.destroyAllWindows()

### Bitwise

In [21]:
bitand=cv2.bitwise_and(gy,ny);
cv2.imshow('image',bitand)
cv2.waitKey(0)
cv2.imwrite('combined_BA.png',bitand)
cv2.destroyAllWindows()

In [22]:
bitor=cv2.bitwise_or(gy,ny);
cv2.imshow('image',bitor)
cv2.waitKey(0)
cv2.imwrite('combined_Bo.png',bitor)
cv2.destroyAllWindows()

In [23]:
bitxor=cv2.bitwise_xor(gy,ny);
cv2.imshow('image',bitxor)
cv2.waitKey(0)
cv2.imwrite('combined_Bxo.png',bitxor)
cv2.destroyAllWindows()